/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import classes.Company;
import classes.Wharehouse;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.concurrent.Semaphore;

/**
 *
 * @author juann
 */
public class MainView extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    Company dell, apple;    
    ConfigurationView configurationView;
    SimulationView simulationView;
    static String[] valuesApple;
    static String[] valuesDell;
    static String dayDuration;
    static String deadline;
    
    public MainView() {
        initComponents();

        MainView.valuesApple = new String[7];
        MainView.valuesDell = new String[7];
        MainView.dayDuration = "";
        MainView.deadline = "";
        
        String currentDir = System.getProperty("user.dir");        
        String path = Paths.get(currentDir, "src", "txtFiles", "config.txt").toString(); 
        File file = new File(path);
        if(file.length() == 0){
            this.configurationView = new ConfigurationView(this.dell, this.apple);
        }
        else{
            try (BufferedReader reader = new BufferedReader(new FileReader(path))) {                                                
                reader.readLine();
                for (int i = 0; i < 7; i++) {
                    valuesApple[i] = reader.readLine();
                }
                reader.readLine();
                for (int i = 0; i < 7; i++) {
                    valuesDell[i] = reader.readLine();
                }
                dayDuration = reader.readLine().split(":")[1];                
                deadline = reader.readLine().split(":")[1];                    
            } catch (IOException e) {
                e.printStackTrace();
            }



            this.configurationView = new ConfigurationView(this.dell, this.apple, valuesApple, valuesDell, dayDuration, deadline);
        }
        
        this.configurationView.setSize(800, 490);
        this.configurationView.setLocation(0, 0);

        body.removeAll();
        body.add(configurationView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();  
        
        
        Semaphore mutex = new Semaphore(1);
        int dayDurationInt = Integer.parseInt(dayDuration);
        int daysToDispatch = Integer.parseInt(deadline);

        int limitWorkersApple = Integer.parseInt(valuesApple[0]);
        int[] requerimentsApple = {2, 1, 4, 4, 2};
        Wharehouse whApple = new Wharehouse(5, requerimentsApple);
        Semaphore employeesMutexApple = new Semaphore(1);
        
        int limitWorkersDell = Integer.parseInt(valuesDell[0]);
        int[] requerimentsDell = {1, 5, 6, 5, 1};
        Wharehouse whDell = new Wharehouse(3, requerimentsDell);
        Semaphore employeesMutexDell = new Semaphore(1);
        
        
        this.simulationView = new SimulationView(configurationView.getValuesApple(), configurationView.getValuesDell(), dayDuration, deadline);
        this.apple = new Company("Apple", limitWorkersApple, whApple, 3, dayDurationInt, 
                daysToDispatch, 100000, 150000, employeesMutexApple, mutex, simulationView);
        
        this.dell = new Company("Dell", limitWorkersDell, whDell, 7, dayDurationInt, 
                daysToDispatch, 80000, 120000, employeesMutexDell, mutex, simulationView); 
        
        this.simulationView.setApple(apple);
        this.simulationView.setDell(dell);
    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        configurationButton = new javax.swing.JButton();
        simulationButton = new javax.swing.JButton();
        exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 490));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        configurationButton.setBackground(new java.awt.Color(204, 255, 255));
        configurationButton.setText("Configuracion");
        configurationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configurationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configurationButtonMouseExited(evt);
            }
        });
        configurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationButtonActionPerformed(evt);
            }
        });
        header.add(configurationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        simulationButton.setBackground(new java.awt.Color(204, 255, 255));
        simulationButton.setText("Simulacion");
        simulationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simulationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simulationButtonMouseExited(evt);
            }
        });
        simulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulationButtonActionPerformed(evt);
            }
        });
        header.add(simulationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 40));

        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("  X");
        exit.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationButtonActionPerformed
        // TODO add your handling code here:                
        configurationView.setSize(800, 490);
        configurationView.setLocation(0, 0);
        
        body.removeAll();
        body.add(configurationView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
        
    }//GEN-LAST:event_configurationButtonActionPerformed

    private void simulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulationButtonActionPerformed
        simulationView.initValues(configurationView.getValuesApple(), configurationView.getValuesDell(), 
                configurationView.getDayDuration().getText(), configurationView.getDeadline().getText());        
        simulationView.setSize(800, 490);
        simulationView.setLocation(0, 0);
        
        body.removeAll();
        body.add(simulationView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_simulationButtonActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        Color color = new Color(255, 51, 51);
        exit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        Color color = new Color(242, 242, 242);
        exit.setBackground(color);
    }//GEN-LAST:event_exitMouseExited

    private void configurationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationButtonMouseEntered
        Color color = new Color(152, 234, 234);
        configurationButton.setBackground(color);
    }//GEN-LAST:event_configurationButtonMouseEntered

    private void configurationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationButtonMouseExited
        Color color = new Color(204, 255, 255);
        configurationButton.setBackground(color);
    }//GEN-LAST:event_configurationButtonMouseExited

    private void simulationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulationButtonMouseEntered
        Color color = new Color(152, 234, 234);
        simulationButton.setBackground(color);
    }//GEN-LAST:event_simulationButtonMouseEntered

    private void simulationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulationButtonMouseExited
        Color color = new Color(204, 255, 255);
        simulationButton.setBackground(color);
    }//GEN-LAST:event_simulationButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton configurationButton;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton simulationButton;
    // End of variables declaration//GEN-END:variables
}
